services:
  app:
    image: node:18-alpine
    container_name: app
    init: true
    tty: true
    working_dir: /src
    volumes:
      - ./app:/src
    env_file: ./app/.env
    environment:
      DB_HOST: db
      DB_SCHEMA: test_db
  db:
    image: mysql
    container_name: db
    env_file: ./db/.env
    environment:
      MYSQL_DATABASE: test_db
    volumes:
      - test-data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  test-data:
